spring:
  security:
    oauth2:
      client:
        registration:
          google:
          client-id: 839540979049-q0v84r0tbcd8etkn7mb55lhadv3tdiid.apps.googleusercontent.com
          client-secret: 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